[package]
name = "rx82"
version = "0.4.0"
edition = "2024"
authors = ["John Arundel <john@bitfieldconsulting.com>"]
description = """An emulator for the RX82 fantasy retro computer system."""
keywords = ["emulator", "emulation", "R8", "RX82", "retrocomputing"]
categories = ["emulators"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/rx82"
homepage = "https://github.com/bitfield/rx82"
repository = "https://github.com/bitfield/rx82"
exclude = ["/.github/"]

[badges]
github = { repository = "bitfield/rx82", workflow = "CI" }
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }

[lints.clippy]
arithmetic_side_effects = "deny"
pedantic = { level = "warn", priority = -1 }
restriction = { level = "warn", priority = -1 }
blanket_clippy_restriction_lints = "allow"
print_stdout = "allow"
pub_use = "allow"
question_mark_used = "allow"
implicit_return = "allow"
missing_docs_in_private_items = "allow" # TODO: remove for release
pub_with_shorthand = "allow"
missing_trait_methods = "allow"
impl_trait_in_params = "allow"
big_endian_bytes = "allow"
little_endian_bytes = "allow"
enum_glob_use = "allow"
unreachable = "allow"
absolute_paths = "allow"
shadow_reuse = "allow"
separated_literal_suffix = "allow"
as_conversions = "allow"
inline_modules = "allow"
